spring:
  cloud:
    config:
      # http://localhost:8888/orderservice-application/default/master
      uri: http://localhost:8888   #config server url
      name: orderservice-application
      label: master
      profile: default    #default/dev/prod
  config:
    import: optional:configserver:http://localhost:8888
