server:
  port: 10086 # server port
spring:
  application:
    name: eurekaserver # eureka server name
eureka:
  client:
    service-url:  # eureka url info
      defaultZone: http://127.0.0.1:10086/eureka